spring:
  application:
    name: ecommerce-be
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update # or 'create', 'create-drop', 'validate', 'none'
    open-in-view: false
server:
  port: ${PORT:8080}
jwt:
  access-token-expiration: 900000 # 15 minutes
  refresh-token-expiration: 604800000 # 7 days
  secret:
    key: ${SECRET}
